### ISSUE TITLE
项目启动报错--hello, you need to fill in two parameters to start the application.

### ISSUE THREAD

**Issue by jpfss** [SwingFrog/Summer#1]
报错信息如下：
hello, you need to fill in two parameters to start the application.

args:
[app jar] [main class]

example:
xxx.jar xxx.xxx.xxx.xxx

看样子要给vm传一个jar包的名字作为参数，后面的我猜应该传ip但是，传了以后继续报错如下：
Connected to the target VM, address: '127.0.0.1:64461', transport: 'socket'
����: �Ҳ������޷��������� Summer.jar
Disconnected from the target VM, address: '127.0.0.1:64461', transport: 'socket'

Process finished with exit code 1
而且没有数据库文件，后面怎么执行？

**Comment by jpfss** [comment]
看了下应该传主类的包名，穿了依旧报上面的错误，乱码的

**Comment by jpfss** [comment]
启动起来了?参数应该传给program params？不过报反射异常，启动失败了具体异常如下（贴一些主要的，应该是反射的问题）：
flect.Method.invoke(Method.java:498)
	at com.swingfrog.summer.app.Summer.main(Summer.java:57)....

**Comment by SwingFrog** [comment]
首先，非常抱歉，现在才注意到你的提问，下次我会注意的。

启动类需要包含main方法，可以看看readme里面的示例

**Comment by jpfss** [comment]
好的，谢谢了，我看看

**Comment by jpfss** [comment]
谢谢，今天下班测试了一下，除了配置文件路径哪里提示找不到配置文件外（已经进行了一次小提交），正常启动了

**Comment by SwingFrog** [comment]
感谢支持！

**Comment by jpfss** [comment]
客气了，非常感谢这个开源作品
