### ISSUE TITLE
服务端重启或者下线怎么处理?

### ISSUE THREAD

**Issue by ggzhangna** [SwingFrog/Summer#11]
分布式部署主要面临的问题,服务端重启或者下线怎么处理?如何重连对用户无感知,有未发送的消息怎么处理?

**Comment by SwingFrog** [comment]
我之前用summer做过个小游戏，前端连接后端，要经过网关。一般情况下更新后端，无需重启网关，这样就可以避免前端断线重连。如果前端跟后端是直连的，那么可以在前端通过一个优化的交互体验平滑过渡断线重连。至于未发送的消息如何处理，如果是业务需求上必须消息百分百发送，那么我觉得可以实现一个消息缓存队列。
