### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by biliskener** [SwingFrog/Summer#14]
我用了你的框架，感觉有一个问题要解决：就是游戏服务器的多线程复杂问题。虽然你分了几个事件队列，但感觉依然解决不了并发的风险问题。我们项目用你的这个框架，在并发问题上放弃了，最后还是回到单线程模型。建议你可以研究一下AKKA和STM。

**Comment by SwingFrog** [comment]
好的，感谢您的建议。在有复杂并发业务的情况下，多线程编程确实令人头疼。我也一直在追寻无锁并发编程，目前有两个问题，如何防止地狱式的回调和减少入队开销。[Summer2](https://github.com/SwingFrog/Summer2) 正在想办法解决此问题....

**Comment by kingo132** [comment]
现在用了summer。。。summer2接口不要改动太大啊，要不然以后迁移到summer会有点悲剧

**Comment by SwingFrog** [comment]
> 现在用了summer。。。summer2优化引擎都没问题，就是接口不要改动太大啊，要不然以后迁移到summer2会有点悲剧

summer2实际上是在解耦summer，当然也有对某些地方进行优化。接口方面确实有变化，通过后期整合或许可以适配，但是新框架还是不够成熟的，依旧需要进行多次迭代才能勉强用用，像summer已经迭代两年多了......

**Comment by SwingFrog** [comment]
> 现在用了summer。。。summer2优化引擎都没问题，就是接口不要改动太大啊，要不然以后迁移到summer2会有点悲剧

啊。。。我刚刚想起来了，你之前建议我加入protobuf .............
