### ISSUE TITLE
建议:增加节点间传输的protobuf

### ISSUE THREAD

**Issue by bobwong89757** [SwingFrog/Summer#16]
目前条件比较有限,如果网关和客户端之间使用protobuf,网关需要转发给其他服务处理业务,最好是直接把protobuf丢到其他节点.但是看到ClientInitializer里面只支持到两种,如果加上protobuf就有意思啦,不过总体来说Summer用起来还是挺舒服

**Comment by SwingFrog** [comment]
首先感谢您的支持。目前summer对rpc远程调用的支持不是很友好，例如没有服务注册中心等。通过网关转发消息，是应该直接转发字节还是先解析协议，再编码发送给后面的业务服，这个还有待商榷，但如果是直接转发使用nginx或许是个不错的选择。

**Comment by bobwong89757** [comment]
> 首先感谢您的支持。目前summer对rpc远程调用的支持不是很友好，例如没有服务注册中心等。通过网关转发消息，是应该直接转发字节还是先解析协议，再编码发送给后面的业务服，这个还有待商榷，但如果是直接转发使用nginx或许是个不错的选择。

嗯,明白,我现在是在网关解析协议再发送的.有个小优化点,网关连接多个client, 如果其中一个client挂了, 轮询机制还会取到那个挂掉的client, 我加了一个检查, 加入client挂了,就移除.

**Comment by tingyanshen** [comment]
> > 首先感谢您的支持。目前summer对rpc远程调用的支持不是很友好，例如没有服务注册中心等。通过网关转发消息，是应该直接转发字节还是先解析协议，再编码发送给后面的业务服，这个还有待商榷，但如果是直接转发使用nginx或许是个不错的选择。
> 
> 嗯,明白,我现在是在网关解析协议再发送的.有个小优化点,网关连接多个client, 如果其中一个client挂了, 轮询机制还会取到那个挂掉的client, 我加了一个检查, 加入client挂了,就移除.

https://github.com/deepinthink/magoko/wiki
