### ISSUE TITLE
StringPasswordLineDecoder有内存泄露

### ISSUE THREAD

**Issue by whxlxl** [SwingFrog/Summer#22]
```java
package com.swingfrog.summer.protocol.stringline 
``` 
包下的 StringPasswordLineDecoder在使用了ByteBuf后未进行资源回收

在server.properties中开启密码验证，使用websocket连接长时间运行后，会导致netty报内存不足。

使用netty自带的工具可以检测出来，启动项目时添加vm参数
-Dio.netty.leakDetectionLevel=PARANOID

建议在StringPasswordLineDecoder.decode增加
```java
ReferenceCountUtil.release(msg);
```

**Comment by SwingFrog** [comment]
已经提交了。
LineBasedFrameDecoder使用不当，不应该直接继承。
LineBasedFrameDecoder做数据切割，然后通过StringPasswordLineDecoder转成字符串。
`            case ProtocolConst.SERVER_PROTOCOL_STRING_LINE:
                pipeline.addLast(new LineBasedFrameDecoder(config.getMsgLength()));
                pipeline.addLast(new StringPasswordLineDecoder(config.getCharset(), config.getPassword()));
                pipeline.addLast(new StringPasswordLineEncoder(config.getCharset(), config.getPassword()));
                pipeline.addLast(new ServerStringHandler(serverContext));
                break;
`

最后，感谢大佬指出问题，并列出详细的数据以及解决方案。
