### ISSUE TITLE
在多服务器下的一些问题和建议

### ISSUE THREAD

**Issue by whxlxl** [SwingFrog/Summer#26]
作者大大你好，这几天我测试了1000人在多服务器下的运作发现几个问题和需要优化的地方
1.Summer.getRandomRemoteClient 这个方法需要优化一下，假如随机拿到一个远程的服务器调用，此时这个服务器如果挂掉，会造成请求超时。建议优化成Summer.（a）syncSendRandomRemoteClitent，当有一台不可用的时候，进行轮询/随机切换到可用的为止
2.多台服务器之间进行连接时，部分服务器会一直不停 remove和add其他服务器，我查看代码貌似发现是一直在不停的触发channelInactive ，触发非常频繁。这个我不清楚是怎么造成的。

**Comment by SwingFrog** [comment]
时隔多年，任是少年？
终于修复了...
