### ISSUE TITLE
能不能加入protobuf协议类型的支持，非常感谢！

### ISSUE THREAD

**Issue by kingo132** [SwingFrog/Summer#5]
现在的json格式性能不太好，对于压力比较大的服务器用起来可能有点困难。
protobuf解析性能是json的8倍，网络流量可以节省3倍，对于用户量特别多的情况，还是protobuf比较现实一些

**Comment by SwingFrog** [comment]
非常抱歉两天后才看到您的建议，首先感谢您对summer提出宝贵的建议！
我一直很想用protobuf来传输数据，但由于框架编码水平不高而且各种逻辑耦合，使得protobuf加入有点困难，于是等我有时间的时候试一试加入吧，如果可以的话，节点间的传输顺便改成protostuff。

**Comment by kingo132** [comment]
不用改太多现有逻辑，只需要在协议类型中增加一种protobuf就行，以前的stringline，lengthfield等等还是能用。我试着加了一下，虽然写得有点丑，但是改动量貌似不太大。

**Comment by SwingFrog** [comment]
好的，您先试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kingo"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 上午9:49
收件人: "SwingFrog/Summer"<Summer@noreply.github.com&gt;; 
抄送: "夕仔"<767214481@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [SwingFrog/Summer] 能不能加入protobuf协议类型的支持，非常感谢！ (#5)




不用改太多现有逻辑，只需要在协议类型中增加一种protobuf就行，以前的stringline，lengthfield等等还是能用。我试着加了一下，虽然写得有点丑，但是改动量貌似不太大。
