### ISSUE TITLE
SessionContext里面保存waitWriteQueue貌似有问题

### ISSUE THREAD

**Issue by kingo132** [SwingFrog/Summer#6]
因为Java对于所有对象都是复制拷贝的，所以如果使用Summer框架的逻辑代码里从框架获取了SessionContext对象，然后再用这个对象去调用syncPushToSessionContext，就会出现重复返回数据包的问题。
譬如逻辑代码是一个函数，函数开头从框架获取了SessionContext sctx；此时sctx里面的waitWriteQueue有5个包，当逻辑代码的函数执行完了，需要向这个sctx推送一条数据。此时逻辑代码里保存的sctx里面还是有5个包，但是框架里可能已经把这5个包都发出去了。此时调用syncPushToSessionContext(stcx)的时候，又会把这5个包重新发出去一次。
我觉得可以考虑把waitWriteQueue移出SessionContext，或者不允许逻辑代码获取SessionContext，或者将所有pushToSessionContext有关的函数都设置成private，不允许逻辑代码调用。

**Comment by SwingFrog** [comment]
首先感谢您对summer的关注。
在summer中sctx (sessionContext) 是与连接绑定的，只要链路还在，sctx就不销毁，也就是说链路仅对应一个sctx。可能您说的是http情况，http协议下每次请求进来都是一个新的链路，也就是每次都会新建个sctx，但返回完会立马销毁。
对于sctx里面的waitWriteQueue这个问题，当链路可写时，会把waitWriteQueue里面的数据包依次写出。

push和响应都是调用以下代码，当链路可写时且队列为空则立刻写出，否则添加到队列中。
```
		if (sctx.getWaitWriteQueueSize() == 0 && ctx.channel().isWritable()) {
			ctx.writeAndFlush(response);
		} else {
			sctx.getWaitWriteQueue().add(response);
		}
```

下面这个是ServerStringHandler里面的代码，当触发可写事件时将队列中的数据包逐个写出。
```
	public void channelWritabilityChanged(ChannelHandlerContext ctx) throws Exception {
		super.channelWritabilityChanged(ctx);
		SessionContext sctx = serverContext.getSessionContextGroup().getSessionByChannel(ctx);
		while (ctx.channel().isActive() && ctx.channel().isWritable() && sctx.getWaitWriteQueueSize() > 0) {
			ctx.writeAndFlush(sctx.getWaitWriteQueue().poll());
		}
	}
```
